package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_30"
    salience 5
when
    $person: PersonDTO( age >= 50, income >= 3000.0, maritalStatus == "Casado" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Plano de Saúde Familiar");
    $b.setRule("beneficio_30.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_30"
    salience 5
when
    $person: PersonDTO( age < 50 || income < 3000.0 || maritalStatus != "Casado" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Plano de Saúde Familiar");
    $b.setRule("beneficio_30.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end
