package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_40"
    salience 5
when
    $person: PersonDTO( age > 50, income >= 3000.0, retired == false, maritalStatus == "Casado" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Plano de Aposentadoria Privada");
    $b.setRule("beneficio_40.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_40"
    salience 5
when
    $person: PersonDTO( age < 50 || income < 3000.0 || retired == true || maritalStatus != "Casado" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Plano de Aposentadoria Privada");
    $b.setRule("beneficio_40.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end