package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_14"
    salience 7
when
    $person: PersonDTO( age >= 30, hasChildren == true, numChildren > 2 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Família");
    $b.setRule("beneficio_14.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_14"
    salience 7
when
    $person: PersonDTO( age < 30 || hasChildren == false || numChildren < 2 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Família");
    $b.setRule("beneficio_14.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end
