package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "Benefício para Imigrantes"
when
    $p : PersonDTO(citizenshipStatus == "Imigrante")
then
    BenefitDTO $b = new BenefitDTO();  
    $b.setBenefit("Auxílio Imigrante");
    $b.setRule("beneficio_09.drl");
    $b.setHasBenefit(true);
    $p.addLisBenefit($b);  
end

rule "Sem Benefício para Imigrantes"
when
    $p : PersonDTO(citizenshipStatus != "Imigrante")
then
    BenefitDTO $b = new BenefitDTO();  
    $b.setBenefit("Auxílio Imigrante");
    $b.setRule("beneficio_09.drl");
    $b.setHasBenefit(false);
    $p.addLisBenefitNot($b);  
end