package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_17"
    salience 4
when
    $person: PersonDTO( age < 18, isWorking == false, hasChildren == true )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Bolsa Família pais menor de idade");
    $b.setRule("beneficio_17.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_17"
    salience 4
when
    $person: PersonDTO( age > 18 || isWorking == true || hasChildren == false )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Bolsa Família pais menor de idade");
    $b.setRule("beneficio_17.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end