package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "Benefício para Trabalhadores com Anos de Contribuição"
when
    $p : PersonDTO(isWorking == true && yearsWorked >= 30)
then
    BenefitDTO $b = new BenefitDTO();  
    $b.setBenefit("Aposentadoria por Tempo de Contribuição");
    $b.setHasBenefit(true);
    $p.addLisBenefit($b);  
end