package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_18"
    salience 3
when
    $person: PersonDTO( age >= 40, hasChildren == true, numChildren == 1 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Creche");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
    System.out.println("Benefício de Auxílio Creche para: " + $person.getName());
end