package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_13"
    salience 8
when
    $person: PersonDTO( age < 60, isWorking == false, creditScore >= 700 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Benefício de Desemprego");
    $b.setRule("beneficio_13.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_13"
    salience 8
when
    $person: PersonDTO(age >= 60 || isWorking == true || creditScore < 700)
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Benefício de Desemprego");
    $b.setRule("beneficio_13.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end