package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_33"
    salience 5
when
    $person: PersonDTO( student == true, income < 1500.0 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Estudante");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
    System.out.println("Benefício de Auxílio Estudante para: " + $person.getName());
end