package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_25"
    salience 9
when
    $person: PersonDTO( age >= 35, maritalStatus == "Casada", numChildren > 2 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Maternidade");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
    System.out.println("Benefício de Auxílio Maternidade para: " + $person.getName());
end