package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_41"
    salience 5
when
    $person: PersonDTO( educationLevel == "Ensino Superior", income >= 5000.0, isWorking == true )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Subsídio de Alta Performance Profissional");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
    System.out.println("Benefício de Subsídio de Alta Performance Profissional para: " + $person.getName());
end