package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_12"
    salience 9
when
    $person: PersonDTO( age >= 60, isWorking == false, creditScore >= 650 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Aposentadoria");
    $b.setRule("beneficio_12.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);    
end

rule "sem beneficio_12"
    salience 9
when
    $person: PersonDTO( age < 60 || isWorking == true || creditScore < 650 )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Aposentadoria");
    $b.setRule("beneficio_12.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);    
end

