package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_44"
    salience 5
when
    $person: PersonDTO( age <= 35, income < 2000.0, retired == false )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Jovem Trabalhador");
    $b.setRule("beneficio_44.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_44"
    salience 5
when
    $person: PersonDTO( age > 35 || income > 2000.0 || retired == true )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Auxílio Jovem Trabalhador");
    $b.setRule("beneficio_44.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end