package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_50"
    salience 5
when
    $person: PersonDTO( age >= 55, income < 2000.0, hasChildren == false, retired == true )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Benefício de Aposentadoria para Baixa Renda");
    $b.setRule("beneficio_50.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_50"
    salience 5
when
    $person: PersonDTO( age < 55 || income > 2000.0 || hasChildren == true || retired == false )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Benefício de Aposentadoria para Baixa Renda");
    $b.setRule("beneficio_50.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end