package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_30"
    salience 5
when
    $person: PersonDTO( age >= 50, income >= 3000.0, maritalStatus == "Casado" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Plano de Saúde Familiar");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
    System.out.println("Benefício de Plano de Saúde Familiar para: " + $person.getName());
end
