package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "Benefício para Pessoas com Doença Grave"
when
    $p : PersonDTO(healthCondition == "Doença Grave")
then
    BenefitDTO $b = new BenefitDTO();  
    $b.setBenefit("Auxílio Doença Grave");
    $b.setRule("beneficio_07.drl");
    $b.setHasBenefit(true);
    $p.addLisBenefit($b);  
end

rule "Sem Benefício para Pessoas com Doença Grave"
when
    $p : PersonDTO(healthCondition != "Doença Grave")
then
    BenefitDTO $b = new BenefitDTO();  
    $b.setBenefit("Auxílio Doença Grave");
    $b.setRule("beneficio_07.drl");
    $b.setHasBenefit(false);
    $p.addLisBenefitNot($b);  
end