package com.example.rules;

import com.motor.decision.dto.PersonDTO;
import com.motor.decision.dto.BenefitDTO;

rule "beneficio_34"
    salience 5
when
    $person: PersonDTO( age > 50, income > 2000.0, maritalStatus == "Viúvo" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Pensão por Morte");
    $b.setRule("beneficio_34.drl");
    $b.setHasBenefit(true);
    $person.addLisBenefit($b);
end

rule "sem beneficio_34"
    salience 5
when
    $person: PersonDTO( age < 50 || income < 2000.0 || maritalStatus != "Viúvo" )
then
    BenefitDTO $b = new BenefitDTO();
    $b.setBenefit("Pensão por Morte");
    $b.setRule("beneficio_34.drl");
    $b.setHasBenefit(false);
    $person.addLisBenefitNot($b);
end